### ISSUE TITLE
Flycast native outputs

### ISSUE THREAD

**Issue by magicray1028** [SeongGino/QMamehook#5]
does flycast native outputs support ammo and damage? i enabled it in settings but all it does is lock up the feedbacks using qmamehooker . using demulshooter with flycast works perfectly though. not sure if theres any specific settings i need to tweak

**Comment by magicray1028** [comment]
ah sorry i just used verbose and figured out its only for lamps, thanks!

**Comment by SeongGino** [comment]
Indeed, Flycast *on its own* does not provide any outputs other than basic LEDs. The only exception to this is Namco's Ninja Assault (`ninjaslt`) which does provide a solenoid feedback channel; I know at least `lamp4` is P1 solenoid, no idea about P2.

If you want controlled ffb with Naomi arcade games, Flycast + DemulShooter hook is your best bet. But you've already figured this out, it seems.

This would've been closed anyways as *not our issue*, but you figured this out before I could comment. Sweep sweep.
