### ISSUE TITLE
Start Minimized

### ISSUE THREAD

**Issue by magicray1028** [SeongGino/QMamehook#6]
Is there any parameter to start Qmamehooker minimized or hide the console window to be front end friendly? currently using ahk to do it but would be great if theres a built in function.

**Comment by SeongGino** [comment]
Also not our issue. Since QMH is a console app, it literally has no connection to or control of the window manager (or in this case, CLI window).

If you don't like how Windows handles this behavior for CLI apps, consider using Linux.
